CN:
  name: A股
  timezone: Asia/Shanghai
  currency: CNY
  calendar_provider: akshare
  default_price_provider: akshare
  trading_hours:
    regular: "09:30-11:30,13:00-15:00"

HK:
  name: 港股
  timezone: Asia/Hong_Kong
  currency: HKD
  calendar_provider: pandas_market_calendars
  default_price_provider: akshare
  trading_hours:
    regular: "09:30-12:00,13:00-16:00"

US:
  name: 美股
  timezone: America/New_York
  currency: USD
  calendar_provider: pandas_market_calendars
  default_price_provider: yfinance
  trading_hours:
    regular: "09:30-16:00"
